// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

namespace CoseSignTool.AzureArtifactSigning.Plugin.Tests;

using Azure;
using Azure.ArtifactSigning.MST;
using CoseSignTool.Abstractions;
using CoseSignTool.AzureArtifactSigning.Plugin;
using Microsoft.Extensions.Configuration;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Moq;
using System.Text.Json;

/// <summary>
/// Tests for <see cref="AzureArtifactSigningSignMstRegisterCommand"/>.
/// </summary>
[TestClass]
public class AzureArtifactSigningSignMstRegisterCommandTests
{
    private const string AasEndpoint = "https://contoso.codesigning.azure.net/";
    private const string ProxyEndpoint = "https://api-canary.northcentralus.codesigning.azure.net/";

    /// <summary>
    /// Verifies that the Artifact Signing command plugin owns the combined sign-and-register command.
    /// </summary>
    [TestMethod]
    public void Plugin_ExposesArtifactSigningSignMstRegisterCommand()
    {
        AzureArtifactSigningCommandPlugin plugin = new();

        IPluginCommand command = plugin.Commands.Single();

        Assert.AreEqual("aas_sign_mst_register", command.Name);
        Assert.IsInstanceOfType<AzureArtifactSigningSignMstRegisterCommand>(command);
    }

    /// <summary>
    /// Verifies that existing registration arguments are retained and only the signing endpoint is added.
    /// </summary>
    [TestMethod]
    public void Options_IncludeSigningAndProxyArguments()
    {
        AzureArtifactSigningSignMstRegisterCommand command = new();

        Assert.IsTrue(command.Options.ContainsKey("endpoint"));
        Assert.IsTrue(command.Options.ContainsKey("proxy-endpoint"));
        Assert.IsTrue(command.Options.ContainsKey("correlation-id"));
        Assert.IsFalse(command.Options.ContainsKey("hash-algorithm"));
        Assert.IsFalse(command.Options.ContainsKey("rsa-signature-padding"));
        Assert.IsFalse(command.Options.ContainsKey("cbor-protected-headers"));
        Assert.AreEqual("azure-artifact-signing", command.CertificateProviderName);
        Assert.IsTrue(command.EmbedPayload);
    }

    /// <summary>
    /// Verifies that the exact statement generated by the generic sign command is registered.
    /// </summary>
    [TestMethod]
    public async Task ExecuteAsync_WithValidArguments_RegistersGeneratedStatement()
    {
        byte[] statementBytes = new byte[] { 0xD2, 0x84, 0x40, 0xA0, 0x40, 0x40 };
        byte[] receiptBytes = new byte[] { 0xD8, 0x63, 0x81, 0x01 };
        string payloadPath = Path.GetTempFileName();
        string signaturePath = Path.Combine(Path.GetTempPath(), $"{Guid.NewGuid():N}.cose");
        string outputPath = Path.Combine(Path.GetTempPath(), $"{Guid.NewGuid():N}.json");
        RecordingTransparencyClient client = new(receiptBytes);
        AzureArtifactSigningSignMstRegisterCommand command = new((_, _, _) => client);
        IConfigurationRoot configuration = CreateConfiguration(
            payloadPath,
            signaturePath,
            outputPath,
            correlationId: "test-correlation-id");

        try
        {
            await File.WriteAllBytesAsync(signaturePath, statementBytes);

            PluginExitCode result = await command.ExecuteAsync(configuration);

            Assert.AreEqual(PluginExitCode.Success, result);
            CollectionAssert.AreEqual(statementBytes, client.SubmittedData);
            Assert.AreEqual("test-account", client.AccountName);
            Assert.AreEqual("test-profile", client.CertificateProfileName);
            Assert.AreEqual("debugruisuprivatetrust", client.MstInstanceName);
            Assert.AreEqual("test-correlation-id", client.CorrelationId);

            using JsonDocument output = JsonDocument.Parse(await File.ReadAllTextAsync(outputPath));
            Assert.AreEqual(
                Convert.ToBase64String(receiptBytes),
                output.RootElement.GetProperty("TransparencyReceipt").GetString());
        }
        finally
        {
            File.Delete(payloadPath);
            File.Delete(signaturePath);
            File.Delete(outputPath);
        }
    }

    /// <summary>
    /// Verifies that registration is not attempted when the generic sign output is missing.
    /// </summary>
    [TestMethod]
    public async Task ExecuteAsync_WithoutGeneratedStatement_DoesNotRegister()
    {
        string payloadPath = Path.GetTempFileName();
        string signaturePath = Path.Combine(Path.GetTempPath(), $"{Guid.NewGuid():N}.cose");
        bool clientCreated = false;
        AzureArtifactSigningSignMstRegisterCommand command = new(
            (_, _, _) =>
            {
                clientCreated = true;
                return new RecordingTransparencyClient(Array.Empty<byte>());
            });
        IConfigurationRoot configuration = CreateConfiguration(payloadPath, signaturePath);

        try
        {
            PluginExitCode result = await command.ExecuteAsync(configuration);

            Assert.AreEqual(PluginExitCode.UserSpecifiedFileNotFound, result);
            Assert.IsFalse(clientCreated);
        }
        finally
        {
            File.Delete(payloadPath);
            File.Delete(signaturePath);
        }
    }

    /// <summary>
    /// Verifies that an account is required before registration starts.
    /// </summary>
    [TestMethod]
    public async Task ExecuteAsync_WithoutAccount_ReturnsMissingRequiredOption()
    {
        AzureArtifactSigningSignMstRegisterCommand command = new(
            (_, _, _) => throw new AssertFailedException("Client should not be created."));
        IConfigurationRoot configuration = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["endpoint"] = "https://debugruisuprivatetrust.confidential-ledger.azure.com",
                ["proxy-endpoint"] = ProxyEndpoint,
                ["aas-endpoint"] = AasEndpoint,
                ["aas-cert-profile-name"] = "test-profile",
                ["PayloadFile"] = "payload.bin",
                ["SignatureFile"] = "statement.cose",
            })
            .Build();

        PluginExitCode result = await command.ExecuteAsync(configuration);

        Assert.AreEqual(PluginExitCode.MissingRequiredOption, result);
    }

    /// <summary>
    /// Verifies that insecure proxy endpoints are rejected.
    /// </summary>
    [TestMethod]
    public async Task ExecuteAsync_WithHttpProxyEndpoint_ReturnsInvalidArgumentValue()
    {
        AzureArtifactSigningSignMstRegisterCommand command = CreateCommandThatMustNotRun();
        IConfigurationRoot configuration = CreateConfiguration(
            "payload.bin",
            "statement.cose",
            proxyEndpoint: "http://api-canary.northcentralus.codesigning.azure.net/");

        PluginExitCode result = await command.ExecuteAsync(configuration);

        Assert.AreEqual(PluginExitCode.InvalidArgumentValue, result);
    }

    /// <summary>
    /// Verifies that invalid timeout values are rejected before file access.
    /// </summary>
    [TestMethod]
    public async Task ExecuteAsync_WithInvalidTimeout_ReturnsInvalidArgumentValue()
    {
        AzureArtifactSigningSignMstRegisterCommand command = CreateCommandThatMustNotRun();
        IConfigurationRoot configuration = CreateConfiguration(
            "payload.bin",
            "statement.cose",
            timeout: "0");

        PluginExitCode result = await command.ExecuteAsync(configuration);

        Assert.AreEqual(PluginExitCode.InvalidArgumentValue, result);
    }

    /// <summary>
    /// Verifies that the command uses the Artifact Signing credential exclusion validation.
    /// </summary>
    [TestMethod]
    public async Task ExecuteAsync_WithUnknownCredentialExclusion_ReturnsInvalidArgumentValue()
    {
        string payloadPath = Path.GetTempFileName();
        string signaturePath = Path.Combine(Path.GetTempPath(), $"{Guid.NewGuid():N}.cose");
        AzureArtifactSigningSignMstRegisterCommand command = CreateCommandThatMustNotRun();
        IConfigurationRoot configuration = CreateConfiguration(
            payloadPath,
            signaturePath,
            excludedCredentials: "UnknownCredential");

        try
        {
            await File.WriteAllTextAsync(payloadPath, "payload");
            await File.WriteAllTextAsync(signaturePath, "statement");

            PluginExitCode result = await command.ExecuteAsync(configuration);

            Assert.AreEqual(PluginExitCode.InvalidArgumentValue, result);
            Assert.IsTrue(File.Exists(signaturePath));
        }
        finally
        {
            File.Delete(payloadPath);
            File.Delete(signaturePath);
        }
    }

    private static AzureArtifactSigningSignMstRegisterCommand CreateCommandThatMustNotRun()
    {
        return new AzureArtifactSigningSignMstRegisterCommand(
            (_, _, _) => throw new AssertFailedException("Client should not be created."));
    }

    private static IConfigurationRoot CreateConfiguration(
        string payloadPath,
        string signaturePath,
        string? outputPath = null,
        string? proxyEndpoint = ProxyEndpoint,
        string? correlationId = null,
        string? timeout = null,
        string? excludedCredentials = null)
    {
        return new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["endpoint"] = "https://debugruisuprivatetrust.confidential-ledger.azure.com",
                ["proxy-endpoint"] = proxyEndpoint,
                ["aas-endpoint"] = AasEndpoint,
                ["aas-account-name"] = "test-account",
                ["aas-cert-profile-name"] = "test-profile",
                ["PayloadFile"] = payloadPath,
                ["SignatureFile"] = signaturePath,
                ["output"] = outputPath,
                ["correlation-id"] = correlationId,
                ["timeout"] = timeout,
                ["aas-exclude-credentials"] = excludedCredentials,
            })
            .Build();
    }

    private sealed class RecordingTransparencyClient : TransparencyClient
    {
        private readonly byte[] receipt;

        public RecordingTransparencyClient(byte[] receipt)
        {
            this.receipt = receipt;
        }

        public string? AccountName { get; private set; }

        public string? CertificateProfileName { get; private set; }

        public string? MstInstanceName { get; private set; }

        public string? CorrelationId { get; private set; }

        public byte[]? SubmittedData { get; private set; }

        public override async Task<Response<Stream>> RegisterTransparencyAsync(
            string codeSigningAccountName,
            string certificateProfileName,
            string mstInstanceName,
            Stream data,
            string xCorrelationId = null,
            CancellationToken cancellationToken = default)
        {
            using MemoryStream submittedData = new();
            await data.CopyToAsync(submittedData, cancellationToken);
            this.AccountName = codeSigningAccountName;
            this.CertificateProfileName = certificateProfileName;
            this.MstInstanceName = mstInstanceName;
            this.CorrelationId = xCorrelationId;
            this.SubmittedData = submittedData.ToArray();

            return Response.FromValue<Stream>(
                new MemoryStream(this.receipt, writable: false),
                Mock.Of<Response>());
        }
    }
}
