#### Re-release Assets ####
# This workflow exists solely to replace the zip files on existing releases, and should only be run manually.
# It updates all of the releases in the given range.

name: Re-release Assets
on:
  workflow_dispatch:
    inputs:
      oldest:
        description: 'Oldest release to include'
        required: true
        default: 'v0.3.1'
      newest:
        description: 'Newest release to include'
        required: true
        default: 'current'

jobs:
  release_assets_by_tag:
    name: release-assets
    runs-on: ${{ matrix.os }}
    permissions:
      actions: write
      contents: write
      deployments: write
      packages: write
      pull-requests: write
      security-events: write
      statuses: write
    strategy:
      matrix:
        include:
          - os: windows-latest
            dir_command: gci -Recurse
            zip_command_debug: Compress-Archive -Path ./debug/ -DestinationPath CoseSignTool-Windows-debug.zip
            zip_command_release: Compress-Archive -Path ./release/ -DestinationPath CoseSignTool-Windows-release.zip
          - os: ubuntu-latest
            dir_command: ls -a -R
            zip_command_debug: zip -r CoseSignTool-Linux-debug.zip ./debug/
            zip_command_release: zip -r CoseSignTool-Linux-release.zip ./release/
          - os: macos-latest
            dir_command: ls -a -R
            zip_command_debug: zip -r CoseSignTool-MacOS-debug.zip ./debug/
            zip_command_release: zip -r CoseSignTool-MacOS-release.zip ./release/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get list of tags
      run: |
        git fetch --quiet
        tags=$(git tag --list --sort=version:refname | awk -v old=${{ github.event.inputs.oldest }} -v new=${{ github.event.inputs.newest }} '$0 >= old && $0 <= new')
        echo "tags = $tags"
        echo "tagsToUpdate=$(echo $tags)" >> $GITHUB_ENV

    - name: Release assets for selected tags
      run: |
        git fetch --tags
        for tag in ${{ env.tagsToUpdate }}; do
          echo "**** Build and publish $tag ****"
          git checkout "$tag"
          dotnet publish --configuration Debug --self-contained true --output published/debug CoseSignTool/CoseSignTool.csproj
          dotnet publish --configuration Release --self-contained true --output published/release CoseSignTool/CoseSignTool.csproj

          echo "**** Copy documentation for $tag ****"
          for folder in debug release; do
            mkdir -p published/$folder/docs
            cp -r docs/* published/$folder/docs/
            cp -r LICENSE published/$folder/
            cp -r *.md published/$folder/
          done

          echo "**** Create zip files for $tag ****"
          ${{ matrix.zip_command_debug }}
          ${{ matrix.zip_command_release }}
          ${{ matrix.dir_command }}

          echo "**** Upload zip files to GitHub ****"
          gh release upload $tag ./published/CoseSignTool-*.zip

        done
